# Generated by Django 5.1 on 2024-11-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0016_rename_decuento_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
