# Generated by Django 5.1 on 2024-10-20 01:39

import django.db.models.deletion
import entidad.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0012_remove_caja_empleado_caja_nombre_cajero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='nombre_cajero',
        ),
        migrations.AddField(
            model_name='caja',
            name='empleado',
            field=models.ForeignKey(default=entidad.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
